version: '3.7'

networks:
  lan:

services:

  neo4j-core1:
    image: neo4j:enterprise
    networks:
      - lan
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
      - 2004:2004
    volumes:
      - ./neo4j/neo4j-core1/conf:/conf
      - ./neo4j/neo4j-core1/data:/data
      - ./neo4j/neo4j-core1/logs:/logs
      - ./neo4j/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
#      - NEO4J_AUTH=none
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=CORE
      - NEO4J_causalClustering_minimumCoreClusterSizeAtFormation=3
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_metrics_prometheus_enabled=true
      - NEO4J_metrics_prometheus_endpoint=0.0.0.0:2004
    restart: unless-stopped

  neo4j-core2:
    image: neo4j:enterprise
    networks:
      - lan
    ports:
      - 7475:7475
      - 6478:6478
      - 7688:7688
      - 2005:2005
    volumes:
      - ./neo4j/neo4j-core2/conf:/conf
      - ./neo4j/neo4j-core2/data:/data
      - ./neo4j/neo4j-core2/logs:/logs
      - ./neo4j/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=CORE
      - NEO4J_causalClustering_minimumCoreClusterSizeAtFormation=3
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7475
      - NEO4J_dbms_connector_https_listen__address=:6478
      - NEO4J_dbms_connector_bolt_listen__address=:7688
      - NEO4J_metrics_prometheus_enabled=true
      - NEO4J_metrics_prometheus_endpoint=0.0.0.0:2005
    restart: unless-stopped

  neo4j-core3:
    image: neo4j:enterprise
    networks:
      - lan
    ports:
      - 7476:7476
      - 6479:6479
      - 7689:7689
      - 2006:2006
    volumes:
      - ./neo4j/neo4j-core3/conf:/conf
      - ./neo4j/neo4j-core3/data:/data
      - ./neo4j/neo4j-core3/logs:/logs
      - ./neo4j/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=CORE
      - NEO4J_causalClustering_minimumCoreClusterSizeAtFormation=3
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7476
      - NEO4J_dbms_connector_https_listen__address=:6479
      - NEO4J_dbms_connector_bolt_listen__address=:7689
      - NEO4J_metrics_prometheus_enabled=true
      - NEO4J_metrics_prometheus_endpoint=0.0.0.0:2006
    restart: unless-stopped

  neo4j-replica1:
    image: neo4j:enterprise
    networks:
      - lan
    ports:
      - 7477:7477
      - 6480:6480
      - 7690:7690
      - 2007:2007
    volumes:
      - ./neo4j/neo4j-replica1/conf:/conf
      - ./neo4j/neo4j-replica1/data:/data
      - ./neo4j/neo4j-replica1/logs:/logs
      - ./neo4j/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=READ_REPLICA
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7477
      - NEO4J_dbms_connector_https_listen__address=:6480
      - NEO4J_dbms_connector_bolt_listen__address=:7690
      - NEO4J_metrics_prometheus_enabled=true
      - NEO4J_metrics_prometheus_endpoint=0.0.0.0:2007
    restart: unless-stopped
            
  prometheus:
    image: prom/prometheus
    networks:
      - lan
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - lan
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    networks:
      - lan
    ports:
      - 3000:3000
    volumes:
      - ./grafana/storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
