{
 "title": "Neo4j dashboard",
 "description": "Neo4j prometheus monitoring dashboard with job filter to change environment",
 "tags": [ "neo4j" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   { "name": "neo4j_instance", "label": "Neo4j instance", "query": "label_values(instance)" },
   {
    "name": "leader",
    "query": "query_result(neo4j_causal_clustering_core_is_leader == 1)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "$neo4j_instance Status",
   "type": "singlestat",
   "description": "Boolean status of the Neo4j server",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "repeat": "neo4j_instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$neo4j_instance Status",
   "type": "singlestat",
   "description": "Boolean status of the Neo4j server",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$neo4j_instance Status",
   "type": "singlestat",
   "description": "Boolean status of the Neo4j server",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$neo4j_instance Status",
   "type": "singlestat",
   "description": "Boolean status of the Neo4j server",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Counters of Graph Items",
   "type": "graph",
   "description": "Total number of graph items: node, relationships, ...",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_ids_in_use_.+\", job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_ids_in_use_(.+)\")",
     "legendFormat": "# {{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Graph Items Creation Rate (ids)",
   "type": "graph",
   "description": "Per-second Average Rate of Increase of Data Counters",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_ids_in_use_node{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "Node rate {{instance}}"
    },
    {
     "expr": "rate(neo4j_ids_in_use_relationship{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "Relationship rate {{instance}}"
    },
    {
     "expr": "rate(neo4j_ids_in_use_property{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "Property rate {{instance}}"
    }
   ]
  },
  {
   "title": "Node creation speed (ids)",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_ids_in_use_node{job='$job', instance=\"$leader\"}[5m])"
    }
   ]
  },
  {
   "title": "Relationship creation speed (ids)",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_ids_in_use_relationship{job=\"$job\", instance=\"$leader\"}[5m])"
    }
   ]
  },
  {
   "title": "Property creation speed (ids)",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_ids_in_use_property{job='$job', instance=\"$leader\"}[5m])"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Last Closed Transaction ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "neo4j_transaction_last_closed_tx_id_total{job='$job', instance=~\"$leader\"}",
     "legendFormat": "Last Closed Write Transaction ID"
    }
   ]
  },
  {
   "title": "Committed Transaction Speed",
   "type": "singlestat",
   "description": "Instant rate",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(neo4j_transaction_committed_total{job='$job', instance=\"$leader\"}[5m])"
    }
   ]
  },
  {
   "title": "Rolled back Transaction Speed",
   "type": "singlestat",
   "description": "Instant rate",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(neo4j_transaction_rollbacks_total{job=\"$job\", instance=\"$leader\"}[5m])"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "All transaction metrics",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_transaction_(started|committed|rollbacks|terminated)_total\", job='$job', instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_transaction_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Committed transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_transaction_committed_total{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "Total Committed Tr.s {{instance}}"
    },
    {
     "expr": "neo4j_transaction_committed_read_total{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "Committed Read Tr.s {{instance}}"
    },
    {
     "expr": "neo4j_transaction_committed_write_total{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "Committed Write Tr.s {{instance}}"
    }
   ]
  },
  {
   "title": "Last Committed Write Transaction ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "neo4j_transaction_last_committed_tx_id_total{job='$job', instance=\"$leader\"}",
     "legendFormat": "Last Committed Transaction ID"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "graph",
   "description": "Active Transactions - Read and Write - \nand Peak concurrent",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_transaction_active.*\", job='$job'}, \"label\", \"$1\", \"__name__\", \"neo4j_transaction_(.+)\")",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "label_replace({__name__=~\"neo4j_transaction_peak.*\", job='$job'}, \"label\", \"$1\", \"__name__\", \"neo4j_transaction_(.+)\")",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Committed Read Transaction Rate",
   "type": "graph",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_read_total{job='$job', instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Committed Write Transaction Rate",
   "type": "graph",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_write_total{job='$job', instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "rate {{instance}}"
    }
   ]
  },
  {
   "title": "Committed Transaction Rate",
   "type": "graph",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_total{job='$job', instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "rate {{instance}}"
    },
    {
     "expr": "irate(neo4j_transaction_committed_total{job='$job', instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "iRate {{instance}}"
    }
   ]
  },
  { "title": "Custom metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Custom metric my-timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_graphaware_neo4j_monitoring_MonitorProcedure_my_timer * 1000"
    }
   ]
  },
  {
   "title": "Custom metric my-counter rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(com_graphaware_neo4j_monitoring_MonitorProcedure_my_counter[5m])",
     "legendFormat": "rate {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt rate of message processing time",
   "type": "graph",
   "description": "Processing and Queuing time per bolt message",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_bolt_accumulated_processing_time_total{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "Processing time per msg {{instance}}"
    }
   ]
  },
  { "title": "Bolt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Bolt Messages",
   "type": "graph",
   "description": "All Bolt Messages (done, failed, received, started)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_messages_.*\", job='$job', instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Messages Queue",
   "type": "graph",
   "description": "Messages received - Messages started",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_bolt_messages_received_total{job='$job', instance=~\"$neo4j_instance\"} - neo4j_bolt_messages_started_total{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "Bolt Msg Queue Length {{instance}}"
    },
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_messages_(received|started)_total\", job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_messages_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Rate of message queue time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_bolt_accumulated_queue_time_total{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_connections_.+\", job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_connections_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_sessions.+\",  job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_sessions_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt rate of message processing time",
   "type": "graph",
   "description": "Processing and Queuing time per bolt message",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_bolt_accumulated_processing_time_total{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "Processing time per msg {{instance}}"
    }
   ]
  },
  { "title": "Page Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Page cache faults",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_page_faults_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache faults/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_page_faults_total{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache Pins and Unpins rate (pins/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_pins_total{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "pins {{instance}}"
    },
    {
     "expr": "rate(neo4j_page_cache_unpins_total{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "unpins {{instance}}"
    }
   ]
  },
  {
   "title": "Page cache evictions rate (evictions/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_evictions_total{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "evictions{{instance}}"
    },
    {
     "expr": "rate(neo4j_page_cache_eviction_exceptions_total{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "eviction exceptions {{instance}}"
    }
   ]
  },
  {
   "title": "Page cache evictions",
   "type": "graph",
   "description": "Eviction process in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_evictions_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache flushes",
   "type": "graph",
   "description": "The total number of flushes executed by the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_flushes_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page Cache Hits",
   "type": "graph",
   "description": "The total number of page hits happened in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_hits_total{job='$job'}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Page Cache Hits Rate (hits/sec)",
   "type": "graph",
   "description": "Per-second Neo4j Page Cache Hits",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_hits_total{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache flushes rate (flushes/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_flushes_total{job=\"$job\", instance=~\"$neo4j_instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page Cache Hit Ratio",
   "type": "graph",
   "description": "The ratio of hits to the total number of lookups in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_hit_ratio{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "graph",
   "description": "Neo4j Checkpoints. \nCheckpointing is the process of flushing all pending page updates from the page cache to the store files",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_check_point_(events|total_time)_total\", job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.*)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoint event duration sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "neo4j_check_point_check_point_duration{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Neo4j Log Rotation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_log_.+\", job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.*)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "VM Garbage Collector",
   "type": "graph",
   "description": "Time and counters",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vm_gc_count_g1_old_generation{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": " {{instance}}"
    },
    {
     "expr": "delta(vm_gc_time_g1_old_generation_total{job=\"$job\", instance=~\"$neo4j_instance\"}[30s])",
     "legendFormat": "delta {{instance}}"
    }
   ]
  },
  {
   "title": "VM Buffer Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 110 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vm_memory_buffer.*\", job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    }
   ]
  },
  {
   "title": "VM Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vm_thread.*\", job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    }
   ]
  },
  {
   "title": "VM Heap Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vm_memory_pool.*\", job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    }
   ]
  },
  { "title": "Causal Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Committed read transaction rate - Leader Vs Others",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_read_total{job=\"$job\", instance=\"$leader\"}[5m])",
     "legendFormat": "Leader {{instance}}"
    },
    {
     "expr": "sum(rate(neo4j_transaction_committed_read_total{job=\"$job\", instance!=\"$leader\"}[5m]))",
     "legendFormat": "Others sum"
    }
   ]
  },
  {
   "title": "Committed write transaction rate - Leader Vs Others",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_write_total{job=\"$job\", instance=\"$leader\"}[5m])",
     "legendFormat": "Leader {{instance}}"
    },
    {
     "expr": "sum(rate(neo4j_transaction_committed_write_total{job=\"$job\", instance!=\"$leader\"}[5m]))",
     "legendFormat": "Others sum"
    }
   ]
  },
  {
   "title": "Core message processing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_causal_clustering_core_message_processing_timer",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicate pulls rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_causal_clustering_read_replica_pull_updates_total[5m])"
    }
   ]
  },
  { "title": "Cypher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Cyper stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_cypher.*\", job='$job'}, \"label\", \"$1\", \"__name__\", \"neo4j_(.+)\")",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } }
 ]
}